# Site settings
title: "Iran University of Science and Technology"
course_name: "Computer Network"
course_description: "This course examines the principles, design, implementation, and performance of computer networks. Students are introduced to the architecture and services of computer networks and layer modeling. This course focuses on Internet networks and the TCP / IP model examines application layer protocols, transport layer, network layer and data link layer."
course_semester: "fall 2019"
description: |
Instructor: Dr. Morteza Analoui

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/Network" # the subpath of your site, e.g. /blog/
url: "https://azadehdarabi.github.io/Network/" # the base hostname & protocol for your site
syllabus: https://azadehdarabi.github.io/Network/syllabus/
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
github_username: azadehdarabi
authorurl: "http://azadehdarabi.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
